name: vitessce-tutorial-env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python==3.8
  - numpy
  - pandas
  - jupyterlab
  - scanpy
  - anndata==0.8.0
  - zarr
  - scipy
  - tifffile
  - pip
  - pip:
    - loompy
    - generate-tiff-offsets
    - leidenalg
    - ome-zarr==0.2.1
    - vitessce[all]==3.0.0